/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DashboardCard: typeof import('./src/components/main/analysis/DashboardCard.vue')['default']
    DashboardCard2: typeof import('./src/components/main/analysis/DashboardCard2.vue')['default']
    DashboardCard3: typeof import('./src/components/main/analysis/DashboardCard3.vue')['default']
    DashboardCard4: typeof import('./src/components/main/analysis/DashboardCard4.vue')['default']
    DashboardCard5: typeof import('./src/components/main/analysis/DashboardCard5.vue')['default']
    DashboardCard6: typeof import('./src/components/main/analysis/DashboardCard6.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    MainBreadcrumbs: typeof import('./src/components/main/mainBreadcrumbs.vue')['default']
    MainHeader: typeof import('./src/components/main/mainHeader.vue')['default']
    MainLeft: typeof import('./src/components/main/mainLeft.vue')['default']
    MainMain: typeof import('./src/components/main/mainMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserContent: typeof import('./src/components/main/user/userContent.vue')['default']
    UserModal: typeof import('./src/components/main/user/userModal.vue')['default']
    UserSearch: typeof import('./src/components/main/user/userSearch.vue')['default']
  }
}
